var level2 = { "height":22,
 "layers":[
        {
         "data":[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 17, 18, 19, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 25, 26, 27, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 33, 34, 35, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 17, 18, 19, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 25, 26, 27, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 33, 34, 35, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 17, 18, 19, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 25, 26, 27, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 33, 34, 35, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12],
         "height":22,
         "name":"bg",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":32,
         "x":0,
         "y":0
        }, 
        {
         "data":[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 51, 51, 51, 51, 51, 51, 51, 51, 51, 0, 0, 0, 51, 51, 51, 51, 51, 0, 0, 51, 0, 0, 51, 51, 51, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0, 51, 0, 0, 0, 51, 51, 51, 51, 0, 0, 51, 0, 51, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0, 51, 0, 0, 0, 0, 0, 0, 51, 0, 0, 51, 0, 51, 0, 0, 0, 0, 0, 0, 0, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 0, 51, 51, 51, 51, 51, 51, 51, 51, 0, 51, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 0, 0, 51, 0, 0, 0, 0, 0, 0, 50, 51, 51, 0, 51, 0, 0, 0, 0, 51, 0, 51, 51, 51, 51, 51, 0, 0, 0, 0, 0, 0, 51, 0, 0, 51, 51, 51, 0, 0, 0, 0, 50, 0, 0, 0, 51, 51, 51, 0, 0, 51, 51, 0, 0, 0, 0, 51, 0, 0, 0, 0, 0, 0, 51, 0, 0, 0, 0, 51, 51, 51, 51, 51, 50, 0, 0, 0, 51, 0, 51, 51, 0, 0, 51, 51, 0, 0, 0, 51, 0, 0, 0, 0, 0, 0, 51, 51, 51, 51, 51, 51, 0, 0, 0, 0, 51, 51, 51, 51, 51, 0, 0, 51, 51, 0, 0, 51, 51, 51, 0, 51, 0, 0, 0, 0, 0, 0, 51, 0, 51, 0, 0, 0, 0, 0, 0, 0, 50, 0, 0, 0, 51, 0, 0, 0, 51, 51, 51, 51, 0, 51, 51, 51, 0, 0, 51, 51, 51, 51, 51, 0, 51, 0, 51, 51, 51, 51, 51, 50, 50, 0, 51, 51, 51, 0, 0, 0, 0, 51, 0, 51, 51, 0, 51, 0, 0, 0, 51, 0, 51, 0, 51, 0, 51, 51, 51, 0, 0, 0, 51, 0, 0, 0, 51, 0, 51, 0, 0, 0, 0, 51, 51, 0, 51, 0, 51, 0, 0, 0, 51, 51, 51, 0, 51, 0, 0, 0, 51, 0, 0, 0, 51, 0, 0, 0, 51, 0, 51, 0, 0, 0, 0, 0, 51, 0, 51, 0, 51, 0, 0, 0, 51, 0, 0, 51, 51, 51, 51, 0, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 0, 0, 0, 0, 51, 0, 51, 51, 51, 51, 0, 0, 51, 0, 0, 51, 0, 0, 51, 0, 51, 0, 0, 0, 51, 0, 0, 0, 0, 51, 0, 51, 51, 51, 51, 51, 51, 0, 51, 0, 51, 0, 0, 0, 51, 0, 0, 51, 51, 51, 51, 0, 51, 0, 0, 0, 51, 0, 0, 0, 0, 51, 0, 0, 0, 0, 0, 0, 0, 0, 51, 0, 51, 32, 0, 0, 51, 51, 51, 51, 0, 0, 51, 51, 51, 50, 51, 50, 51, 51, 50, 50, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 0, 0, 0, 51, 0, 0, 51, 0, 0, 51, 0, 51, 0, 51, 0, 0, 51, 0, 0, 51, 0, 0, 0, 51, 0, 0, 51, 0, 0, 0, 0, 51, 0, 0, 0, 51, 0, 0, 51, 51, 51, 51, 0, 51, 0, 51, 51, 51, 51, 0, 51, 51, 51, 0, 0, 51, 51, 51, 51, 51, 51, 51, 0, 51, 0, 0, 0, 51, 0, 0, 0, 0, 0, 51, 0, 51, 0, 51, 0, 0, 51, 51, 51, 0, 51, 0, 51, 51, 0, 51, 0, 0, 0, 51, 51, 51, 0, 0, 0, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 0, 0, 0, 51, 0, 0, 51, 51, 51, 0, 0, 51, 51, 51, 51, 51, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         "height":22,
         "name":"maze",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":32,
         "x":0,
         "y":0
        }, 
        {
         "height":22,
         "name":"obstacles",
         "objects":[
                {
                 "ellipse":true,
                 "height":19,
                 "name":"player",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":20,
                 "x":38,
                 "y":37
                }, 
                {
                 "ellipse":true,
                 "height":24,
                 "name":"goal",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":25,
                 "x":964,
                 "y":485
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":320,
                 "y":96
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":256,
                 "y":352
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":576,
                 "y":320
                }, 
                {
                 "height":256,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":32,
                 "y":64
                }, 
                {
                 "height":160,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":64,
                 "y":160
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":192,
                 "y":160
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":224,
                 "x":96,
                 "y":64
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":224,
                 "y":128
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":352,
                 "y":32
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":480,
                 "y":64
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":512,
                 "y":128
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":576,
                 "y":128
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":192,
                 "x":576,
                 "y":96
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":608,
                 "y":32
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":704,
                 "y":32
                }, 
                {
                 "height":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":800,
                 "y":64
                }, 
                {
                 "height":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":864,
                 "y":32
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":640,
                 "y":160
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":640,
                 "y":192
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":704,
                 "y":192
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":736,
                 "y":224
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":768,
                 "y":256
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":800,
                 "y":288
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":832,
                 "y":192
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":864,
                 "y":224
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":864,
                 "y":256
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":928,
                 "y":256
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":192,
                 "x":288,
                 "y":160
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":352,
                 "y":192
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":448,
                 "y":256
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":448,
                 "y":224
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":352,
                 "y":256
                }, 
                {
                 "height":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":192,
                 "y":288
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":128,
                 "y":384
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":128,
                 "y":352
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":64,
                 "y":352
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":64,
                 "y":416
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":160,
                 "y":448
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":256,
                 "y":288
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":256,
                 "y":320
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":224,
                 "y":384
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":256,
                 "y":416
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":288,
                 "y":480
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":320,
                 "y":448
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":320,
                 "y":352
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":448,
                 "y":352
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":512,
                 "y":288
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":512,
                 "y":320
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":576,
                 "y":256
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":512,
                 "y":192
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":576,
                 "y":160
                }, 
                {
                 "height":192,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":640,
                 "y":224
                }, 
                {
                 "height":192,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":672,
                 "y":256
                }, 
                {
                 "height":160,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":704,
                 "y":288
                }, 
                {
                 "height":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":736,
                 "y":320
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":768,
                 "y":384
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":800,
                 "y":320
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":896,
                 "y":320
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":896,
                 "y":416
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":896,
                 "y":448
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":960,
                 "y":320
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":928,
                 "y":448
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":608,
                 "y":448
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":224,
                 "x":640,
                 "y":480
                }, 
                {
                 "height":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":832,
                 "y":352
                }, 
                {
                 "height":160,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":960,
                 "y":512
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":864,
                 "y":640
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":768,
                 "y":608
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":768,
                 "y":544
                }, 
                {
                 "height":65,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":155,
                 "x":448,
                 "y":448
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":800,
                 "y":544
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":896,
                 "y":576
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":512,
                 "x":256,
                 "y":544
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":160,
                 "y":512
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":128,
                 "y":512
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":64,
                 "y":544
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":128,
                 "y":608
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":192,
                 "y":640
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":256,
                 "y":576
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":384,
                 "y":608
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":448,
                 "y":640
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":480,
                 "y":576
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":512,
                 "y":640
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":608
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":608,
                 "y":576
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":672,
                 "y":640
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":704,
                 "y":608
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":960,
                 "y":448
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":640,
                 "y":576
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":256,
                 "y":224
                }, 
                {
                 "height":704,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":0,
                 "y":0
                }, 
                {
                 "height":704,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":992,
                 "y":0
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":960,
                 "x":32,
                 "y":0
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":960,
                 "x":32,
                 "y":672
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":32,
         "x":0,
         "y":0
        }],
 "orientation":"orthogonal",
 "properties":
    {

    },
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "image":"tilesetmap3.png",
         "imageheight":256,
         "imagewidth":256,
         "margin":0,
         "name":"tilesetmap3",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":32,
         "tilewidth":32
        }],
 "tilewidth":32,
 "version":1,
 "width":32
}