var levelmap = { "height":20,
 "layers":[
        {
         "data":[200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
         "height":20,
         "name":"bg",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":30,
         "x":0,
         "y":0
        }, 
        {
         "data":[138, 453, 452, 452, 452, 452, 452, 452, 452, 452, 0, 0, 0, 452, 452, 452, 452, 452, 0, 0, 452, 0, 0, 452, 452, 452, 292, 293, 294, 295, 0, 453, 1420, 0, 0, 0, 0, 0, 0, 452, 0, 1404, 0, 452, 0, 0, 0, 452, 452, 452, 452, 0, 0, 452, 1420, 452, 320, 321, 322, 323, 1462, 453, 0, 0, 1356, 0, 0, 0, 1340, 452, 0, 0, 0, 452, 0, 0, 0, 0, 0, 0, 452, 1356, 0, 452, 0, 452, 348, 349, 350, 351, 1478, 453, 453, 453, 453, 452, 452, 453, 453, 453, 453, 453, 453, 453, 453, 1336, 452, 452, 453, 453, 453, 453, 453, 453, 0, 452, 0, 0, 0, 0, 0, 0, 0, 0, 453, 0, 0, 453, 0, 0, 0, 0, 0, 0, 452, 452, 452, 1436, 453, 0, 0, 0, 0, 453, 1340, 452, 452, 452, 452, 452, 292, 293, 294, 295, 453, 0, 0, 453, 453, 453, 1436, 0, 0, 0, 453, 0, 0, 0, 453, 452, 452, 0, 0, 453, 453, 0, 0, 1356, 0, 452, 320, 321, 322, 323, 453, 1340, 0, 0, 1356, 452, 452, 452, 452, 452, 453, 0, 0, 1356, 453, 0, 452, 452, 0, 0, 453, 453, 0, 0, 1436, 452, 348, 349, 350, 351, 453, 453, 452, 453, 453, 453, 0, 0, 0, 1420, 452, 452, 452, 452, 453, 0, 0, 452, 452, 1420, 0, 453, 452, 452, 0, 452, 0, 0, 0, 0, 452, 0, 452, 0, 0, 0, 1345, 0, 0, 0, 453, 0, 0, 1340, 453, 1404, 0, 0, 452, 452, 452, 453, 0, 452, 452, 452, 452, 452, 452, 452, 452, 0, 452, 0, 453, 453, 453, 453, 452, 453, 453, 0, 452, 452, 453, 0, 0, 0, 0, 452, 0, 453, 453, 0, 452, 0, 452, 0, 452, 0, 452, 0, 452, 452, 453, 0, 0, 0, 452, 0, 0, 0, 452, 0, 453, 173, 174, 175, 176, 452, 452, 0, 453, 0, 452, 0, 452, 452, 452, 1336, 452, 0, 0, 1356, 453, 0, 0, 1336, 452, 0, 0, 1436, 452, 0, 453, 201, 202, 203, 204, 0, 452, 0, 453, 0, 452, 1356, 452, 0, 0, 453, 453, 453, 453, 0, 452, 453, 453, 453, 452, 453, 453, 453, 453, 452, 452, 452, 230, 231, 232, 0, 452, 0, 453, 452, 452, 452, 452, 0, 0, 453, 0, 0, 453, 0, 452, 0, 0, 0, 452, 0, 1404, 0, 0, 452, 0, 452, 452, 452, 452, 452, 452, 0, 453, 0, 452, 0, 452, 1436, 0, 452, 452, 452, 452, 0, 452, 1340, 0, 0, 452, 0, 0, 0, 1420, 452, 0, 0, 0, 0, 372, 1356, 0, 0, 453, 0, 453, 138, 452, 452, 452, 452, 0, 0, 452, 453, 452, 453, 452, 453, 452, 452, 453, 453, 452, 453, 453, 453, 453, 453, 453, 453, 453, 453, 453, 452, 453, 0, 452, 0, 0, 453, 1420, 0, 452, 1404, 452, 0, 452, 0, 0, 452, 0, 1340, 452, 0, 0, 1336, 452, 0, 0, 452, 1420, 0, 0, 0, 453, 0, 452, 1419, 0, 453, 453, 453, 453, 0, 452, 0, 452, 463, 463, 463, 0, 463, 463, 463, 0, 0, 453, 453, 452, 453, 453, 453, 453, 1336, 453, 1462, 452, 0, 0, 1340, 0, 0, 453, 0, 452, 0, 453, 183, 183, 463, 463, 463, 0, 463, 0, 453, 453, 0, 452, 1404, 372, 0, 453, 453, 453, 1478, 452, 452, 452, 452, 452, 452, 453, 453, 453, 453, 453, 1356, 0, 0, 452, 183, 183, 453, 453, 453, 0, 0, 452, 452, 452, 452, 452, 0, 372, 372],
         "height":20,
         "name":"maze",
         "opacity":1,
         "type":"tilelayer",
         "visible":true,
         "width":30,
         "x":0,
         "y":0
        }, 
        {
         "height":20,
         "name":"obstacles",
         "objects":[
                {
                 "ellipse":true,
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":0,
                 "y":0
                }, 
                {
                 "ellipse":true,
                 "height":32,
                 "name":"player",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":0,
                 "y":0
                }, 
                {
                 "ellipse":true,
                 "height":32,
                 "name":"goal",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":928,
                 "y":448
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":288,
                 "y":64
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":192,
                 "y":96
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":128,
                 "y":352
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":96,
                 "y":480
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":160,
                 "y":608
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":320,
                 "y":512
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":416,
                 "y":512
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":512,
                 "y":512
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":640,
                 "y":512
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":736,
                 "y":512
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":864,
                 "y":480
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":224,
                 "y":320
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":256,
                 "y":448
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":256,
                 "y":512
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":384,
                 "y":416
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":640,
                 "y":64
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":96
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":768,
                 "y":256
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":608,
                 "y":160
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":832,
                 "y":224
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":896,
                 "y":416
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":224
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":832,
                 "y":608
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":288
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":864,
                 "y":384
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":416,
                 "y":192
                }, 
                {
                 "height":256,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":0,
                 "y":32
                }, 
                {
                 "height":160,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":32,
                 "y":128
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":160,
                 "y":128
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":224,
                 "x":64,
                 "y":32
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":192,
                 "y":96
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":320,
                 "y":0
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":448,
                 "y":32
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":480,
                 "y":96
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":96
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":192,
                 "x":544,
                 "y":64
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":576,
                 "y":0
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":672,
                 "y":0
                }, 
                {
                 "height":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":768,
                 "y":32
                }, 
                {
                 "height":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":832,
                 "y":0
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":608,
                 "y":128
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":608,
                 "y":160
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":672,
                 "y":160
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":704,
                 "y":192
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":736,
                 "y":224
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":768,
                 "y":256
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":800,
                 "y":160
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":832,
                 "y":192
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":832,
                 "y":224
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":896,
                 "y":224
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":192,
                 "x":256,
                 "y":128
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":320,
                 "y":160
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":0,
                 "x":416,
                 "y":192
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":416,
                 "y":224
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":416,
                 "y":192
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":320,
                 "y":224
                }, 
                {
                 "height":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":160,
                 "y":256
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":96,
                 "y":352
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":96,
                 "y":320
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":32,
                 "y":320
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":32,
                 "y":384
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":128,
                 "y":416
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":224,
                 "y":256
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":224,
                 "y":288
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":224,
                 "y":288
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":192,
                 "y":352
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":224,
                 "y":384
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":256,
                 "y":448
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":288,
                 "y":416
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":288,
                 "y":320
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":416,
                 "y":320
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":480,
                 "y":256
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":480,
                 "y":288
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":224
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":224
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":480,
                 "y":160
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":544,
                 "y":128
                }, 
                {
                 "height":192,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":608,
                 "y":192
                }, 
                {
                 "height":192,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":640,
                 "y":224
                }, 
                {
                 "height":160,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":672,
                 "y":256
                }, 
                {
                 "height":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":704,
                 "y":288
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":736,
                 "y":352
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":768,
                 "y":288
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":864,
                 "y":288
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":864,
                 "y":384
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":864,
                 "y":416
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":928,
                 "y":288
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":896,
                 "y":416
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":576,
                 "y":416
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":224,
                 "x":608,
                 "y":448
                }, 
                {
                 "height":128,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":800,
                 "y":320
                }, 
                {
                 "height":160,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":928,
                 "y":480
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":832,
                 "y":608
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":736,
                 "y":576
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":736,
                 "y":512
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":416,
                 "y":416
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":128,
                 "x":768,
                 "y":512
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":864,
                 "y":544
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":512,
                 "x":224,
                 "y":512
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":128,
                 "y":480
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":96,
                 "y":480
                }, 
                {
                 "height":96,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":32,
                 "y":512
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":96,
                 "y":576
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":160,
                 "y":608
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":96,
                 "x":224,
                 "y":544
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":352,
                 "y":576
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":416,
                 "y":608
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":448,
                 "y":544
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":480,
                 "y":608
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":512,
                 "y":576
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":512,
                 "y":576
                }, 
                {
                 "height":64,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":576,
                 "y":544
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":640,
                 "y":608
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":672,
                 "y":576
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":928,
                 "y":416
                }, 
                {
                 "height":0,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"",
                 "visible":true,
                 "width":32,
                 "x":608,
                 "y":576
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":32,
                 "x":608,
                 "y":544
                }, 
                {
                 "height":32,
                 "name":"",
                 "properties":
                    {

                    },
                 "type":"fixture",
                 "visible":true,
                 "width":64,
                 "x":224,
                 "y":192
                }],
         "opacity":1,
         "type":"objectgroup",
         "visible":true,
         "width":30,
         "x":0,
         "y":0
        }],
 "orientation":"orthogonal",
 "properties":
    {

    },
 "tileheight":32,
 "tilesets":[
        {
         "firstgid":1,
         "image":"tilesets\/arctographer-windows.png",
         "imageheight":596,
         "imagewidth":916,
         "margin":0,
         "name":"arctographer-windows",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":32,
         "tilewidth":32
        }, 
        {
         "firstgid":505,
         "image":"tilesets\/equipment-icons-tileset.png",
         "imageheight":512,
         "imagewidth":512,
         "margin":0,
         "name":"equipment-icons-tileset",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":32,
         "tilewidth":32
        }, 
        {
         "firstgid":761,
         "image":"tilesets\/custom_tileset_by_boomxbig-d4rh1c1.png",
         "imageheight":555,
         "imagewidth":900,
         "margin":0,
         "name":"custom_tileset_by_boomxbig-d4rh1c1",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":32,
         "tilewidth":32
        }, 
        {
         "firstgid":1237,
         "image":"tilesets\/TileB_Forest_1.png",
         "imageheight":512,
         "imagewidth":512,
         "margin":0,
         "name":"TileB_Forest_1",
         "properties":
            {

            },
         "spacing":0,
         "tileheight":32,
         "tilewidth":32
        }],
 "tilewidth":32,
 "version":1,
 "width":30
}